# Generated by Django 3.2.7 on 2021-09-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField(max_length=100000)),
                ('status', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('noteType', models.CharField(default='personal', max_length=100)),
                ('theDate', models.CharField(max_length=20)),
            ],
        ),
    ]
