# Generated by Django 3.2.7 on 2021-09-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='memster',
            field=models.CharField(default='Private', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='noteType',
            field=models.CharField(default='Personal', max_length=100),
        ),
    ]
